config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/destroy'
  get 'profile/show'
  get 'profile/edit'

  get 'assignments/list'
  get 'assignments/show'
  get 'assignments/new'
  post 'assignments/create'
  get 'assignments/edit'
  get 'assignments/update'
  get 'assignments/delete'

  get 'courses/list'
  get 'courses/show'
  get 'courses/new'
  post 'courses/create'
  get 'courses/edit'
  get 'courses/update'
  get 'courses/delete'

  get 'home/index'
  root 'home#index'

  resources :courses
  resources :assignments
  resources :users

  get '/login',to: 'sessions#new'
  get '/logout',to: 'sessions#destroy'
  post '/login',to: 'sessions#create'
  get '/list_for_course/:id', to:'assignments#list_for_course'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :name ,presence: true
  belongs_to :course, optional: true
  has_one :student
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name ,presence: true
  has_many :assignments, dependent: :destroy
  has_one :teacher, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  validates :classNo ,presence: true
  has_one :user ,dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :levelNo ,presence: true
  has_one :user ,dependent: :destroy
  has_many :courses, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :username ,presence: true
  validates :fullname ,presence: true
  validates :dateOfBirth ,presence: true
  has_one :teacher
  has_one :student

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

   # Confirms a logged-in user.
   def logged_in_user
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url

     end
   end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  before_action :logged_in_user, only: [:create, :update]

  def index
    @assignments = Assignment.all
  end

  def list
    @assignments = []
    if teacher_user?
      if @course
        @assignments = @course.assignments
      end
    else
      @user = current_user
      @student = Student.find_by(user_id: @user.id)
      #debugger
      @assignments = Assignment.where("student_id = ?", @student.id)
    end
  end

  def list_for_course
    @course = Course.find(params[:id])
    @assignments = @course.assignments
    render 'assignments/list'
  end

  def show
    @assignment = Assignment.find(params[:id])
    @student = Student.find_by(id: @assignment.student_id)
    @student = User.find_by(id: @student.user_id)
    @course = @assignment.course
  end

  def new
    @students = []
    Student.all.each do |s|
      @user = User.find_by(id: s.user_id)
      @user.id = s.id
      @students << @user
    end
    @assignment = Assignment.new
    @course = Course.find(params[:id])
    @assignment.course_id = @course.id
    #@course = Course.find(params[:id])
  end

  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.course_id = assignment_params[:course_id]
    if @assignment.save
        flash.now[:success] = "Assignment Successfully saved"
        list
    else
        flash.now[:danger] = "Assignment Not Saved"
        render 'new'
    end

  end

  def edit
    @assignment = Assignment.find(params[:id])
    @students = []
    Student.all.each do |s|
      @user = User.find_by(id: s.user_id)
      @user.id = s.id
      @students << @user
    end
  end

  def update
    @assignment = Assignment.find(assignment_params[:id])
    if @assignment.update_attributes(assignment_params)
      flash[:success] = "Assignment updated!"
      redirect_to @assignment
    end
  end

  def destroy
    @assignment =  Assignment.find(params[:id])
    @course = Course.find_by(id: @assignment.course_id)
    @assignment.delete
    @assignments = @course.assignments
    render 'assignments/list'
  end

  private
  def assignment_params
    params.require(:assignment).permit(:id, :name, :course_id, :student_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :logged_in_user, except: :list

  def index
    @courses = Course.all
  end

  def list
    @courses ||= []

    #@teacher = Teacher.find_by(user_id: current_user.id)

    #@courses = Course.where("teacher_id = ?", @teacher.id)
    @courses = Course.all
    #debugger
  end

  def show
    @course = Course.find(params[:id])
    @teacher = Teacher.find_by(id: @course.teacher_id)
  end

  def new
    @course = Course.new
    @user = current_user
    @teacher = Teacher.find_by(user_id: @user.id)
    @course.teacher_id = @teacher.id
  end

  def create
    @course = Course.new(course_params)
    DeliveryBoy.deliver_async(course_params.to_json, topic: "courses")

  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(course_params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course updated!"
      redirect_to @course
    else
        flash.now[:danger] = "Course Not updated due to empty name"
        render 'edit'
    end
  end

  def destroy
    @assignments = Assignment.where("course_id = ?", params[:id])
    if @assignments
      @assignments.each do |a|
        a.delete
      end
    end
    Course.find(params[:id]).delete
    redirect_to courses_list_url
  end


  private
  def course_params
    params.require(:course).permit(:id, :name, :teacher_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  def index
    #redirect_to courses_list_url
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def show
      @user = current_user

      if teacher_user?
        @profile = Teacher.find_by(user_id: @user.id)
        @profile_type = "Teacher"
      else
        @profile = Student.find_by(user_id: @user.id)
        @profile_type = "Student"
      end
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to home_index_url
    end
  end

  def create
    #debugger
    user = User.find_by(username: params[:session][:username])
    if user
      reset_session
      log_in user
      redirect_to home_index_url
    else
      flash.now[:danger] = 'Invalid Username' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to home_index_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def teacher_user?
    if logged_in?
      Teacher.exists?(user_id: session[:user_id])
    end
  end

  def student_user?
    if logged_in?
      Student.exists?(User_id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

 # Logs out the current user.
  def log_out
    reset_session
    @current_user = nil
  end
end

app/views/assignments/_assignment.html.erb
<tr>
  <td>
      <%= assignment.name %>
  </td>
  <td>
      <%= assignment.created_at %>
  </td>
  <td>
      <%= assignment.updated_at %>
  </td>
  <td>
    <%= link_to 'View', assignment, id: assignment.id %>

    <% if teacher_user? %>
      <%= link_to 'Edit', controller: "assignments", action: "edit", id: assignment.id  %>
      <%= link_to 'Delete', assignment, :method => "delete", :confirm=>"Are you sure?" %>
    <% end %>
  </td>
</tr>

app/views/assignments/create.html.erb
<h1>Assignments#create</h1>
<p>Find me in app/views/assignments/create.html.erb</p>

app/views/assignments/delete.html.erb
<h1>Assignments#delete</h1>
<p>Find me in app/views/assignments/delete.html.erb</p>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>
<%= form_with(url: assignments_edit_path, model: @assignment, local: true) do |f| %>
  <table>
    <tr>
      <th><%= f.label :name %></th>
      <td>:</td>
      <td><%= f.text_field :name%></td>
    </tr>
    <tr>
      <th><%= f.label :Student %></th>
      <td>:</td>
      <td>
        <%= f.select "student_id" , options_from_collection_for_select(@students, "id", "username", @assignment.student_id)
        %>

      </td>
    </tr>
    <tr>
      <th><%= f.hidden_field :id %></td>
        <td></td>
      <td><%= f.submit "Update"%></td>
    </tr>
  </table>

<% end %>

app/views/assignments/list.html.erb
<h1>Assignments</h1>

<table>
    <tr>
      <th>Name </th>
      <th>Created At </th>
      <th>Updated At </th>
      <th>Actions </th>
    </tr>

    <% if @assignments %>
      <%= render @assignments %>
    <% end %>

</table>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>
<%= form_with(url: assignments_create_path, model: @assignment, local: true) do |f| %>
  <table>
    <tr>
      <th><%= f.label :name %></th>
      <td>:</td>
      <td><%= f.text_field :name%></td>
    </tr>

    <tr>
      <th><%= f.label :Student %></th>
      <td>:</td>
      <td>
        <%= f.select "student_id", options_from_collection_for_select(@students, "id", "username")
        %>

      </td>
    </tr>
    <tr>
      <th><%= f.hidden_field :course_id %></td>
        <td></td>
      <td><%= f.submit "Create"%></td>
    </tr>
  </table>

<% end %>

app/views/assignments/show.html.erb
<h1>Assignment</h1>

<div>
  <table>
    <tr>
      <th>Name</th>
      <td>:</td>
      <td><%= @assignment.name %></td>
    </tr>
    <tr>
      <th>Course</th>
      <td>:</td>
      <td><%= @course.name %></td>
    </tr>

    <tr>
      <th>Assigned To</th>
      <td>:</td>
      <td><%= @student.username %></td>
    </tr>
    <tr>
      <th>Created At</th>
      <td>:</td>
      <td><%= @assignment.created_at %></td>
    </tr>
    <tr>
      <th>Updated At</th>
      <td>:</td>
      <td><%= @assignment.updated_at %></td>
    </tr>
  </table>
  <br>
  <%= link_to 'Back', :back %>
</div>

app/views/assignments/update.html.erb
<h1>Assignments#update</h1>
<p>Find me in app/views/assignments/update.html.erb</p>

app/views/courses/_course.html.erb
<tr>
  <td>
      <%= course.name %>
  </td>
  <td>
      <%= course.created_at %>
  </td>
  <td>
      <%= course.updated_at %>
  </td>
  <td>
    <%= link_to 'View', course, id: course.id %>
    <% if teacher_user? %>
      <%= link_to 'Edit', controller: "courses", action: "edit", id: course.id  %>
      <%= link_to 'Delete', course, :method => "delete", :confirm=>"Are you sure?" %>
    <% end %>
  </td>
</tr>

app/views/courses/delete.html.erb
<h1>Courses#delete</h1>
<p>Find me in app/views/courses/delete.html.erb</p>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>
<%= form_with(url: courses_update_path, model: @course, local: true) do |f| %>
<table>
  <tr>
    <th><%= f.label :name %></th>
    <td>:</td>
    <td><%= f.text_field :name%></td>
  </tr>
  <tr>
    <th><%= f.hidden_field :id %></td>
      <td></td>
    <td><%= f.submit "Update"%></td>
  </tr>
</table>
<% end %>

app/views/courses/list.html.erb
<h1>Courses</h1>

<% if logged_in? %>
  <table>
      <tr>
        <th>Name </th>
        <th>Created At </th>
        <th>Updated At </th>
        <th>Actions </th>

      </tr>

      <% if @courses %>
        <%= render @courses %>
      <% end %>

  </table>
  <br>
  <%= link_to "Add New Course", courses_new_path %>
<% else %>
You must log in
<%= link_to 'Log in', login_path %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>
<%= form_with(url: courses_create_path, model: @course, local: true) do |f| %>
  <table>
    <tr>
      <th><%= f.label :name %></th>
      <td>:</td>
      <td><%= f.text_field :name%></td>
    </tr>

    <tr>
      <th><%= f.hidden_field :teacher_id %></th>
      <td></td>
      <td><%= f.submit "Create"%></td>

    </tr>
  </table>

<% end %>

app/views/courses/show.html.erb
<h1>Course</h1>
<div>
  <table>
    <tr>
      <th>Name</th>
      <td>:</td>
      <td><%= @course.name %></td>
    </tr>
    <tr>
      <th>Owner</th>
      <td>:</td>
      <td><%= current_user.username %></td>
    </tr>

    <tr>
      <th>Created At</th>
      <td>:</td>
      <td><%= @course.created_at %></td>
    </tr>
    <tr>
      <th>Updated At</th>
      <td>:</td>
      <td><%= @course.updated_at %></td>
    </tr>
    <tr>
      <th>No of Assignments</th>
      <td>:</td>
      <td><%= @course.assignments.length %></td>
    </tr>
  </table>
  <br>
    <%= link_to "Assignments", controller: "assignments", action: "list_for_course", id: @course.id %>

    <%= link_to 'Add Assignment', controller: "assignments", action: "new", id: @course.id %>

    <%= link_to 'Back', :back %>
  <br>

</div>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>

app/views/home/index.html.erb
<h1>Home</h1>

<div>
    <% if logged_in? %>
      <ul>
          <% if teacher_user? %>
            <li>
              <%= link_to "Courses", courses_list_path %>
            </li>
          <% end %>
          <% if student_user? %>
            <li>
              <%= link_to "Assignments", assignments_list_path %>
            </li>
          <% end %>
      </ul>
    <% else %>
      You must log in
      <%= link_to 'Log in', login_path %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniSchoolSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <% if logged_in? %>
        <%= link_to 'Home', home_index_path %>  |
        <%= link_to current_user.username , profile_show_path %>  |
        <%= link_to 'Log out', logout_path %>
      <% end %>


      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
  </body>
</html>